### ISSUE TITLE
update documentation for how to update web site and send email when site has problems.

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-docs#12]
- [ ] location of login information for web site
- [ ] how to backup wordpress site before changes
- [ ] 3 locations to change using elementor
- [ ] save files
- [ ] which mailing list to send notification to
- [ ] who has approval or how to release mail

**Comment by larsks** [comment]
Depends on https://github.com/CCI-MOC/ops-issues/issues/187

**Comment by msdisme** [comment]
Overtaken by git automation. f
