### ISSUE TITLE
Create format for collecting and storing University and other contact information

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-docs#8]
- [x] Make/locate a directory
- [x] Discuss - is the directory public or private?
- Private
- [x] Discuss is it just universities, or place for HW partners?
- Any contact information, university, hardware partners, and internal
- [x] first case is northeastern - use as trial run: https://github.com/CCI-MOC/ops-issues/issues/13
- [x] update policies to make it official where we store contact information.
- [PR](https://github.com/CCI-MOC/ops-docs/pull/24)

**Comment by msdisme** [comment]
I am not likely to get to this till after the conference, @joachimweyl  and I will discuss to see if I should hand it off.

**Comment by joachimweyl** [comment]
location should be [here](https://github.com/CCI-MOC/ops-private/tree/main/contacts)

**Comment by joachimweyl** [comment]
PR created just needs a sign off.
